services:
  slurm-dev:
    build: 
      context: .
      dockerfile: Containerfile
    container_name: slurm-dev-env
    hostname: slurm-test-node
    tty: true 
    stdin_open: true
    volumes:
      # Mount the current directory (containing the source code) to /slurm-src
      - .:/slurm-src
      # Mount a specific folder for your configuration files
      - ./slurm-conf:/etc/slurm
    command: >
      /bin/bash -c "sudo -u munge /usr/sbin/munged && tail -f /dev/null"
