ClusterName=dev-cluster
ControlMachine=slurm-test-node
SlurmUser=slurm
SlurmdUser=root

AuthType=auth/munge
SlurmctldPort=6817
SlurmdPort=6818

StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldDebug=debug3
SlurmdDebug=debug3

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
GresTypes=gpu

ResMemPerGPU=10240 

NodeName=slurm-test-node CPUs=4 RealMemory=32000 Gres=gpu:2 State=UNKNOWN

PartitionName=debug Nodes=slurm-test-node Default=YES MaxTime=INFINITE State=UP
